services:
  app:
    build: .
    container_name: user-management-app
    env_file:
      - .env
    environment:
      - SCRIPTS_PATH=/app/scripts
      - WINRM_SERVER=mailzone.central.st-ing.com
      - WINRM_PORT=5985
      - EXCHANGE_SERVER=mailzone.central.st-ing.com
    volumes:
      - app_data:/app/data
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    restart: unless-stopped
    # user: "1000:1000"  # Закомментировано для избежания проблем с правами
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: user-management-frontend
    ports:
      - "0.0.0.0:8080:80"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  app_data:

networks:
  app-network:
    driver: bridge